INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10001, 'jongwon', 'Get AWS Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10002, 'jongwon', 'Get Azure Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10003, 'jongwon', 'Get GCP Certified', CURRENT_DATE(), false);

INSERT INTO todo(ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES(10004, 'jongwon', 'Learn DevOps', CURRENT_DATE(), false);

